<%

  def boxen?; ENV['BOXEN_HOME']; end

  url  = ENV["BOXEN_POSTGRESQL_URL"]
  port = ENV["BOXEN_POSTGRESQL_PORT"]
  user = ENV["RAILS_DB_USER"]
  pass = ENV["RAILS_DB_PASS"]
  db   = ENV["RAILS_DB_NAME"] || 'didh_development'

%>

common: &common
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 50
  port: <%= port %>
  user: <%= user %>
  database: <%= db %>
  password: <%= pass %>

production:
  <<: *common

development:
  <<: *common
  database: <%= db %>

test:
  <<: *common
  database: didh_test

